// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: get.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_get_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=Kind" json:"kind,omitempty"`
	// Types that are assignable to Data:
	//
	//	*GetResponse_Text
	//	*GetResponse_Binary
	//	*GetResponse_Credentials
	//	*GetResponse_Card
	Data isGetResponse_Data `protobuf_oneof:"Data"`
	ID   string             `protobuf:"bytes,6,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_get_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_UNSPECIFIED
}

func (m *GetResponse) GetData() isGetResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *GetResponse) GetText() string {
	if x, ok := x.GetData().(*GetResponse_Text); ok {
		return x.Text
	}
	return ""
}

func (x *GetResponse) GetBinary() []byte {
	if x, ok := x.GetData().(*GetResponse_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *GetResponse) GetCredentials() *Credentials {
	if x, ok := x.GetData().(*GetResponse_Credentials); ok {
		return x.Credentials
	}
	return nil
}

func (x *GetResponse) GetCard() *Card {
	if x, ok := x.GetData().(*GetResponse_Card); ok {
		return x.Card
	}
	return nil
}

func (x *GetResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type isGetResponse_Data interface {
	isGetResponse_Data()
}

type GetResponse_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type GetResponse_Binary struct {
	Binary []byte `protobuf:"bytes,3,opt,name=binary,proto3,oneof"`
}

type GetResponse_Credentials struct {
	Credentials *Credentials `protobuf:"bytes,4,opt,name=credentials,proto3,oneof"`
}

type GetResponse_Card struct {
	Card *Card `protobuf:"bytes,5,opt,name=card,proto3,oneof"`
}

func (*GetResponse_Text) isGetResponse_Data() {}

func (*GetResponse_Binary) isGetResponse_Data() {}

func (*GetResponse_Credentials) isGetResponse_Data() {}

func (*GetResponse_Card) isGetResponse_Data() {}

var File_get_proto protoreflect.FileDescriptor

var file_get_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x73, 0x61, 0x76,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x22, 0xbf, 0x01, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x19, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x05, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x30, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x48,
	0x00, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x1b,
	0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x43,
	0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x42, 0x06, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_get_proto_rawDescOnce sync.Once
	file_get_proto_rawDescData = file_get_proto_rawDesc
)

func file_get_proto_rawDescGZIP() []byte {
	file_get_proto_rawDescOnce.Do(func() {
		file_get_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_proto_rawDescData)
	})
	return file_get_proto_rawDescData
}

var file_get_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_proto_goTypes = []any{
	(*GetRequest)(nil),  // 0: GetRequest
	(*GetResponse)(nil), // 1: GetResponse
	(Kind)(0),           // 2: Kind
	(*Credentials)(nil), // 3: Credentials
	(*Card)(nil),        // 4: Card
}
var file_get_proto_depIdxs = []int32{
	2, // 0: GetResponse.kind:type_name -> Kind
	3, // 1: GetResponse.credentials:type_name -> Credentials
	4, // 2: GetResponse.card:type_name -> Card
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_get_proto_init() }
func file_get_proto_init() {
	if File_get_proto != nil {
		return
	}
	file_save_proto_init()
	file_card_proto_init()
	file_get_proto_msgTypes[1].OneofWrappers = []any{
		(*GetResponse_Text)(nil),
		(*GetResponse_Binary)(nil),
		(*GetResponse_Credentials)(nil),
		(*GetResponse_Card)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_proto_goTypes,
		DependencyIndexes: file_get_proto_depIdxs,
		MessageInfos:      file_get_proto_msgTypes,
	}.Build()
	File_get_proto = out.File
	file_get_proto_rawDesc = nil
	file_get_proto_goTypes = nil
	file_get_proto_depIdxs = nil
}
