// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: save.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_UNSPECIFIED Kind = 0
	Kind_CARD        Kind = 1
	Kind_TEXT        Kind = 2
	Kind_CREDENTIALS Kind = 3
	Kind_BINARY      Kind = 4
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CARD",
		2: "TEXT",
		3: "CREDENTIALS",
		4: "BINARY",
	}
	Kind_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CARD":        1,
		"TEXT":        2,
		"CREDENTIALS": 3,
		"BINARY":      4,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_save_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_save_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{0}
}

type Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_save_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=Kind" json:"kind,omitempty"`
	// Types that are assignable to Data:
	//
	//	*SaveRequest_Text
	//	*SaveRequest_Binary
	//	*SaveRequest_Credentials
	//	*SaveRequest_Card
	Data isSaveRequest_Data `protobuf_oneof:"Data"`
	Meta string             `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_save_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{1}
}

func (x *SaveRequest) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_UNSPECIFIED
}

func (m *SaveRequest) GetData() isSaveRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SaveRequest) GetText() string {
	if x, ok := x.GetData().(*SaveRequest_Text); ok {
		return x.Text
	}
	return ""
}

func (x *SaveRequest) GetBinary() []byte {
	if x, ok := x.GetData().(*SaveRequest_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *SaveRequest) GetCredentials() *Credentials {
	if x, ok := x.GetData().(*SaveRequest_Credentials); ok {
		return x.Credentials
	}
	return nil
}

func (x *SaveRequest) GetCard() *Card {
	if x, ok := x.GetData().(*SaveRequest_Card); ok {
		return x.Card
	}
	return nil
}

func (x *SaveRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type isSaveRequest_Data interface {
	isSaveRequest_Data()
}

type SaveRequest_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type SaveRequest_Binary struct {
	Binary []byte `protobuf:"bytes,3,opt,name=binary,proto3,oneof"`
}

type SaveRequest_Credentials struct {
	Credentials *Credentials `protobuf:"bytes,4,opt,name=credentials,proto3,oneof"`
}

type SaveRequest_Card struct {
	Card *Card `protobuf:"bytes,5,opt,name=card,proto3,oneof"`
}

func (*SaveRequest_Text) isSaveRequest_Data() {}

func (*SaveRequest_Binary) isSaveRequest_Data() {}

func (*SaveRequest_Credentials) isSaveRequest_Data() {}

func (*SaveRequest_Card) isSaveRequest_Data() {}

type SaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_save_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_save_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_save_proto_rawDescGZIP(), []int{2}
}

func (x *SaveResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_save_proto protoreflect.FileDescriptor

var file_save_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x61,
	0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xc3, 0x01, 0x0a, 0x0b, 0x53, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x62, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x12, 0x30, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x1b, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x04, 0x63,
	0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x1e, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x2a,
	0x48, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x41, 0x52, 0x44,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x52, 0x45, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x53, 0x10, 0x03, 0x12, 0x0a, 0x0a,
	0x06, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x04, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x6f, 0x70,
	0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_save_proto_rawDescOnce sync.Once
	file_save_proto_rawDescData = file_save_proto_rawDesc
)

func file_save_proto_rawDescGZIP() []byte {
	file_save_proto_rawDescOnce.Do(func() {
		file_save_proto_rawDescData = protoimpl.X.CompressGZIP(file_save_proto_rawDescData)
	})
	return file_save_proto_rawDescData
}

var file_save_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_save_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_save_proto_goTypes = []any{
	(Kind)(0),            // 0: Kind
	(*Credentials)(nil),  // 1: Credentials
	(*SaveRequest)(nil),  // 2: SaveRequest
	(*SaveResponse)(nil), // 3: SaveResponse
	(*Card)(nil),         // 4: Card
}
var file_save_proto_depIdxs = []int32{
	0, // 0: SaveRequest.kind:type_name -> Kind
	1, // 1: SaveRequest.credentials:type_name -> Credentials
	4, // 2: SaveRequest.card:type_name -> Card
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_save_proto_init() }
func file_save_proto_init() {
	if File_save_proto != nil {
		return
	}
	file_card_proto_init()
	file_save_proto_msgTypes[1].OneofWrappers = []any{
		(*SaveRequest_Text)(nil),
		(*SaveRequest_Binary)(nil),
		(*SaveRequest_Credentials)(nil),
		(*SaveRequest_Card)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_save_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_save_proto_goTypes,
		DependencyIndexes: file_save_proto_depIdxs,
		EnumInfos:         file_save_proto_enumTypes,
		MessageInfos:      file_save_proto_msgTypes,
	}.Build()
	File_save_proto = out.File
	file_save_proto_rawDesc = nil
	file_save_proto_goTypes = nil
	file_save_proto_depIdxs = nil
}
